# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: none
relative_permalinks: true
lsi: true

baseurl: "/"

timezone: "Europe/Paris"

paginate: 5
paginate_path: 'page:num'

categories_path: categories
tags_path: tags
