# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: true

# Setup
title: 'Management en territoire hostile'
description: ''
url: 'http://management.chioetto.fr/'
baseurl: '/'

author:
  name: 'Morgane Chioetto'
  linkedin: 'morgane-chioetto/82/1a6/623'
  email_md5: '4f3f5003188ae984047ce4ba500c131f'

paginate: 5
paginate_path: 'page:num'

rss_path: feed.xml
categories_path: categories
tags_path: tags
