# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: true

# Setup
title: 'Management en territoire hostile'
description: 'Blog personnel de réflexions sur le management et les idées reçues sur les bonnes méthodes pour manager une équipe.'
url: 'http://management.chioetto.fr/'
baseurl: '/'

paginate: 5
paginate_path: 'page:num'

rss_path: feed.xml
categories_path: categories
tags_path: tags
