# Dependencies
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments

# Permalinks
permalink: /:categories/:title
relative_permalinks: true
lsi: true

baseurl: "/"

timezone: "Europe/Paris"

paginate: 5
paginate_path: 'page:num'

categories_path: categories
tags_path: tags
